# Generated by Django 4.2.5 on 2023-09-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filmes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filme",
            name="genero",
        ),
        migrations.AlterField(
            model_name="filme",
            name="review",
            field=models.CharField(
                blank=True,
                help_text="Digite um breve review do filme",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="filme",
            name="sinopse",
            field=models.CharField(
                blank=True,
                help_text="Digite o titulo do filme",
                max_length=200,
                null=True,
            ),
        ),
    ]
