# Generated by Django 4.2.4 on 2023-09-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Entre o nome', max_length=100)),
                ('idade', models.IntegerField(help_text='Entre a idade')),
                ('email', models.EmailField(help_text='Informe o email', max_length=254)),
                ('gender', models.CharField(help_text='Informe o seu gênero', max_length=15)),
                ('dtNasc', models.DateField(help_text='Nascimento no formato DD/MM/AAAA', verbose_name='Data de nascimento')),
            ],
        ),
    ]
