# Generated by Django 4.2.4 on 2023-09-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='gender',
        ),
        migrations.AddField(
            model_name='usuario',
            name='sex',
            field=models.CharField(default=3, help_text='Informe o seu sexo', max_length=15),
            preserve_default=False,
        ),
    ]
