# Generated by Django 4.2.5 on 2023-09-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0002_remove_usuario_gender_usuario_sex"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuario",
            old_name="nome",
            new_name="username",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="dtNasc",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="sex",
        ),
        migrations.AddField(
            model_name="usuario",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(
                help_text="Informe o email", max_length=254, unique=True
            ),
        ),
    ]
