# Generated by Django 4.2.5 on 2023-09-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "usuarios",
            "0003_rename_nome_usuario_username_remove_usuario_dtnasc_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="idade",
            field=models.IntegerField(blank=True, help_text="Entre a idade", null=True),
        ),
    ]
